Repository hygieia/hygieia-whitesource-collector, pull requests merged in 2020-08, with the labels that each got.

#6 Updated documentation
  README.md
Labels: ✅ Approved

#7 ChangeRequestLog to collect change set for org
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/Constants.java
  src/main/java/com/capitalone/dashboard/collector/DefaultWhiteSourceClient.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceClient.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceCollectorTask.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceSettings.java
  src/main/java/com/capitalone/dashboard/repository/WhiteSourceCustomComponentRepository.java
Labels: ✅ Approved, 🔍 Ready for Review

#8 GetProjectVitals for evaluation timestamp
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/Constants.java
  src/main/java/com/capitalone/dashboard/collector/DefaultWhiteSourceClient.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceClient.java
Labels: ✅ Approved

#9 License severity from alerts
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/DefaultWhiteSourceClient.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceSettings.java
  src/main/java/com/capitalone/dashboard/model/LicensePolicyType.java
Labels: ✅ Approved

#10 Added new endpoint
  pom.xml
  src/main/java/com/capitalone/dashboard/Application.java
  src/main/java/com/capitalone/dashboard/collector/Constants.java
  src/main/java/com/capitalone/dashboard/collector/DefaultWhiteSourceClient.java
  src/main/java/com/capitalone/dashboard/config/WebMVCConfig.java
  src/main/java/com/capitalone/dashboard/controller/DefaultWhiteSourceController.java
  src/main/java/com/capitalone/dashboard/model/WhiteSourceRequest.java
  src/main/java/com/capitalone/dashboard/repository/CollectorItemRepository.java
  src/test/java/com.capitalone.dashboard/controller/DefaultWhiteSourceControllerTest.java
Labels: ✅ Approved

#12 updated version
  pom.xml
Labels: 🔍 Ready for Review

#13 changed timestamp value
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/DefaultWhiteSourceClient.java
  src/main/java/com/capitalone/dashboard/collector/RestOperationsSupplier.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceSettings.java
  src/main/java/com/capitalone/dashboard/controller/DefaultWhiteSourceController.java
Labels: ✅ Approved

#14 Added token in collectoritem query
  pom.xml
  src/main/java/com/capitalone/dashboard/collector/DefaultWhiteSourceClient.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceCollectorTask.java
  src/main/java/com/capitalone/dashboard/collector/WhiteSourceSettings.java
  src/main/java/com/capitalone/dashboard/repository/CollectorItemRepository.java
Labels: ✅ Approved
